### ISSUE TITLE
REQ#18 - Imagen 9gag

### ISSUE THREAD

**Issue by fscarpello** [Alan-Mathison-Turing/Asistente_Virtual#22]
Como usuario quiero pedirle al asistente una imagen al azar de 9gag para ilustrar mis conversaciones. 10pts.

**Comment by axellab** [comment]
API 9GAG: https://github.com/k3min/infinigag

**Comment by axellab** [comment]
https://github.com/NeonArtworks/9-Search

**Comment by fscarpello** [comment]
Finalizado en branch 9gag
