### ISSUE TITLE
Las estructuras try/catch no deberian utilizarse para manejar flujo

### ISSUE THREAD

**Issue by delucas** [Alan-Mathison-Turing/Asistente_Virtual#38]
https://github.com/Alan-Mathison-Turing/Asistente_Virtual/blob/fd8daf53e69d4ea62381094447eb91b4e38fcdb1/backend/main/java/edu/unlam/asistente/asistente_virtual/Bot.java#L44

**Comment by fscarpello** [comment]
Resuelto en branch "bugfix". 
* Se generó una nueva clase denominada Default.
* Default implementa la interfaz IDecision y queda como última clase a invocar en Chain of Responsability, retornando el mensaje genérico de "no entendí lo que quisiste decir".
