### ISSUE TITLE
Evaluar la posibilidad de reformar este código

### ISSUE THREAD

**Issue by delucas** [Alan-Mathison-Turing/Asistente_Virtual#39]
https://github.com/Alan-Mathison-Turing/Asistente_Virtual/blob/fd8daf53e69d4ea62381094447eb91b4e38fcdb1/backend/main/java/edu/unlam/asistente/calculadora/Calculadora.java#L142

**Comment by of-utos** [comment]
Se refactorizó el método para que no haya tanto código repetido.
