### ISSUE TITLE
REQ#9 - Datos del Clima en Tiempo Real

### ISSUE THREAD

**Issue by fscarpello** [Alan-Mathison-Turing/Asistente_Virtual#51]
Como usuario quiero pedirle al asistente los datos del clima en tiempo real para saber si debo utilizar o no paraguas. 6pts. Debe ser de la locación actual, o de la solicitada.

**Comment by of-utos** [comment]
Se logra obtener datos del clima en tiempo real, desde el clima en una ciudad o si va a llover en esa misma ciudad u otra.
